<a href="https://colab.research.google.com/github/VitikaJain25/HealthCareNLPCourse/blob/main/Tensorflow_%26_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Tensorflow is Deep Learning Package.
import tensorflow as tf
# Keras is based on Tensorflow & it supports high end APIs.
import tensorflow.keras as keras

# Tensor is N-Dimentional representation of array of data for various ranks like scalar:tensor(Rank 0), vector:tensor(Rank 1), Matrix(Rank 2), Tensor(3 or More).


In [2]:
# Creating a constant of scalar type
# scalar with tensor rank = 0, shape =0, dtype = int32 bits
# numpy indicates the value.
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
# scalar with tensor rank = 0, shape = 0, dtype = int8 (-128 to 127)
const_1 = tf.constant(127, dtype = 'int8')
print(const_1)

tf.Tensor(127, shape=(), dtype=int8)


In [4]:
const_1.numpy()

127

In [5]:
# Shows the tensor shape
const_1.shape

TensorShape([])

## Vectors

In [6]:
# Vector with Rank = 1
const_2 = tf.constant([20., 40., 60., 80., 15], dtype = 'float16')
print(const_2)

tf.Tensor([20. 40. 60. 80. 15.], shape=(5,), dtype=float16)


In [7]:
# tensor rank = 1
const_2.shape

TensorShape([5])

In [8]:
const_3 = tf.constant([20, 40, 60, 80, 15], dtype = 'int16')
print(const_3)

tf.Tensor([20 40 60 80 15], shape=(5,), dtype=int16)


In [9]:
# Changing / Typecasting the data type.
tf.cast(const_3, dtype = 'int32')

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([20, 40, 60, 80, 15], dtype=int32)>

In [10]:
# Typecasting from one tensor data type to another.
tf.cast(const_3, dtype = 'float32')

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([20., 40., 60., 80., 15.], dtype=float32)>

## Tensor Matrix

In [11]:
# Vector with rank = 2
const_4 = tf.constant([[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]], dtype = 'int16')
print(const_4)

tf.Tensor(
[[220 120 260]
 [112 150 190]
 [220 240 180]], shape=(3, 3), dtype=int16)


In [12]:
const_4.shape

TensorShape([3, 3])

In [13]:
const_4.numpy()

array([[220, 120, 260],
       [112, 150, 190],
       [220, 240, 180]], dtype=int16)

## Tensor N-D Array

In [14]:
const_5 = tf.constant([[[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]],
                      [[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]]], dtype = 'int16')
print (const_5)

tf.Tensor(
[[[220 120 260]
  [112 150 190]
  [220 240 180]]

 [[220 120 260]
  [112 150 190]
  [220 240 180]]], shape=(2, 3, 3), dtype=int16)


### Variable Declaration

In [15]:
var_1 = tf.Variable(10, dtype = 'int8')
print(var_1)

<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=10>


In [16]:
# To access the value
var_1.numpy()

10

In [17]:
var_2 = tf.Variable([2., 4., 5., 7., 11., 15.], dtype = 'float16')
print(var_2)

<tf.Variable 'Variable:0' shape=(6,) dtype=float16, numpy=array([ 2.,  4.,  5.,  7., 11., 15.], dtype=float16)>


In [18]:
var_3 = tf.Variable([[[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]],
                      [[220, 120, 260],
                      [112, 150, 190],
                      [220, 240, 180]]], dtype = 'int16')
print(var_3)

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int16, numpy=
array([[[220, 120, 260],
        [112, 150, 190],
        [220, 240, 180]],

       [[220, 120, 260],
        [112, 150, 190],
        [220, 240, 180]]], dtype=int16)>


 Difference between Constant and Variable - Variable can be changed.

## Mathematical Operations

In [19]:
# Y = WT * X + bias
Weights = tf.Variable([[10],
                      [12],
                      [15],
                      [9],
                      [18],
                      [12]], dtype = 'float16')
print(Weights)

<tf.Variable 'Variable:0' shape=(6, 1) dtype=float16, numpy=
array([[10.],
       [12.],
       [15.],
       [ 9.],
       [18.],
       [12.]], dtype=float16)>


In [20]:
X = tf.Variable([[10],
                 [12],
                 [15],
                 [9],
                 [18],
                 [12]], dtype = 'float16')
print(X)

<tf.Variable 'Variable:0' shape=(6, 1) dtype=float16, numpy=
array([[10.],
       [12.],
       [15.],
       [ 9.],
       [18.],
       [12.]], dtype=float16)>


In [21]:
# Shape for Weights and X is 6x1. We cannot multiply these unless we Transpose.
WT = tf.transpose(Weights)
print(WT)

tf.Tensor([[10. 12. 15.  9. 18. 12.]], shape=(1, 6), dtype=float16)


In [22]:
# Y = W * X
tf.tensordot(X, WT, axes = 1)

<tf.Tensor: shape=(6, 6), dtype=float16, numpy=
array([[100., 120., 150.,  90., 180., 120.],
       [120., 144., 180., 108., 216., 144.],
       [150., 180., 225., 135., 270., 180.],
       [ 90., 108., 135.,  81., 162., 108.],
       [180., 216., 270., 162., 324., 216.],
       [120., 144., 180., 108., 216., 144.]], dtype=float16)>

In [23]:
# Y = WT * X
tf.tensordot(WT, X, axes = 1)

<tf.Tensor: shape=(1, 1), dtype=float16, numpy=array([[1018.]], dtype=float16)>

### Using Keras - Deep Learning API

In [24]:
import tensorflow.keras as keras
keras.__version__

'2.8.0'

In [25]:
# Dense Neural Network
from tensorflow.keras.layers import Dense
# Sequential Connection of Neural Network
from tensorflow.keras.models import Sequential
# Optimizers
from tensorflow.keras.optimizers import RMSprop

In [26]:
# input shape = number of features
# units = number of neurons
# number of neurons in input layer (4) is lower than number of neurons in hidden layer (8).
# using relu activation function for input and hidden layer

def build_model():
  # Sequential Neural Network - FeedForward Neural Network
  model = Sequential()
  model.add(Dense(units = 4, activation = 'relu', input_shape = [3]))
  # Hidden layer - 1
  model.add(Dense(units = 8, activation = 'relu'))
  # Output Layer - For Regression
  model.add(Dense(units = 1))
  # Model Compiler
  model.compile(loss = 'mean_squared_error', optimizer = 'RMSprop', metrics = ['mean_squared_error',
                                                                                'mean_absolute_error'])
  return model

In [27]:
model = build_model()

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 16        
                                                                 
 dense_1 (Dense)             (None, 8)                 40        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 65
Trainable params: 65
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Parameters = Total number of weights and biases.